source/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from api.views import get_token_view, ChosenAddView, ChoosenRemoveView
# from .views import QuoteViewSet

app_name = 'api'

router = DefaultRouter()
# router.register(r'chosen', ChosenAddView)
# router.register(r'product', ProductViewSet)
# router.register(r'user', UserViewSet)
# router.register(r'orders', OrderViewSet)

urlpatterns = [
    path('get-token/', get_token_view, name='get_token'),
    path('', include(router.urls)),
    path('chosen/', include([
        path('add', ChosenAddView.as_view(), name='chosen_add'),
        path('remove/', ChoosenRemoveView.as_view(), name="chosen_delete"),
    ])),
]

source/main/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('webapp.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/', include('api.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path, include
from webapp.views import IndexView, PhotoView, PhotoCreateView, PhotoUpdateView, PhotoDeleteView, PhotoChosenView, PhotoRemoveView

app_name = 'webapp'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),

    path('photo/', include([
        path('<int:pk>/', include([
            path('', PhotoView.as_view(), name='photo_view'),
            path('update/', PhotoUpdateView.as_view(), name='photo_update'),
            path('delete/', PhotoDeleteView.as_view(), name='photo_delete'),
            path('chosen/', PhotoChosenView.as_view(), name='photo_choose'),
            path('remove/', PhotoRemoveView.as_view(), name='photo_remove'),
        ])),
        path('create/', PhotoCreateView.as_view(), name='photo_create'),
    ])),
]

source/webapp/models.py
from django.contrib.auth import get_user_model
from django.db import models


class Photo(models.Model):
    image = models.ImageField(upload_to='pics', verbose_name='Фотография')
    signature = models.CharField(max_length=100, verbose_name='Название')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
    author = models.ForeignKey(get_user_model(), on_delete=models.SET_DEFAULT, default=1,
                               related_name='photos', verbose_name='Автор')

    def chosen_by(self, user):
        user = self.chosens.filter(user=user)
        return user.count() > 0

    def __str__(self):
        return f"{self.author} -- {self.signature}"

    class Meta:
        verbose_name = 'Фотография'
        verbose_name_plural= 'Фотографии'


class Chosen(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE,
                               related_name='user_chosen', verbose_name='Пользователь')

    image = models.ForeignKey('webapp.Photo', on_delete=models.CASCADE,
                              related_name='chosens', verbose_name='избр. фотография')

    class Meta:
        verbose_name = 'Избранная фотография'
        verbose_name_plural = 'Избранные фотографии'

source/webapp/forms.py
from django import forms
from webapp.models import Photo


class SearchForm(forms.Form):
    search = forms.CharField(max_length=100, required=False, label="Найти")


class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ['image', 'signature']

source/webapp/views/base_views.py
from django.db.models import Q
from django.views.generic import ListView as DjangoListView
from webapp.forms import SearchForm


class SearchView(DjangoListView):
    search_form_class = SearchForm
    search_form_field = 'search'
    search_fields = []

    def get(self, request, *args, **kwargs):
        self.search_form = self.get_search_form()
        self.search_value = self.get_search_value(self.search_form)
        return super().get(request, *args, **kwargs)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['search_form'] = self.search_form
        context['search_value'] = self.search_value
        return context

    def get_queryset(self):
        data = super(SearchView, self).get_queryset()
        query = self.get_query(self.search_value)
        data = data.filter(query)
        return data

    def get_search_form(self):
        return self.search_form_class(data=self.request.GET)

    def get_search_value(self, form):
        search_value = None
        if form.is_valid():
            search_value = form.cleaned_data.get(self.search_form_field, None)
        return search_value

    def get_query(self, search_value):
        query = Q()
        if search_value:
            for field in self.search_fields:
                kwargs = {field: search_value}
                query = query | Q(**kwargs)
        return query

source/webapp/views/photo_views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, \
    UserPassesTestMixin
from django.core.paginator import Paginator
from django.http import HttpResponse, HttpResponseForbidden
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.utils.timezone import make_naive
from django.views.generic import View, DetailView, CreateView, UpdateView, DeleteView

from webapp.models import Photo, Chosen
from webapp.forms import PhotoForm
from .base_views import SearchView


class IndexView(SearchView):
    template_name = 'photos/index.html'
    context_object_name = 'photos'
    paginate_by = 9
    paginate_orphans = 0
    model = Photo
    ordering = ['-created_at']
    search_fields = ['signature__icontains', 'author__icontains']

    def get_queryset(self):
        data = super().get_queryset()
        # if not self.request.GET.get('is_admin', None):
        #     data = data.filter(status='moderated')
        return data


class PhotoView(DetailView):
    model = Photo
    template_name = 'photos/photo_view.html'

    # чтоб товары, которых не осталось нельзя было и просмотреть
    # это можно добавить вместо model = Product в Detail, Update и Delete View.
    def get_queryset(self):
        return super().get_queryset()


class PhotoCreateView(LoginRequiredMixin, CreateView):
    template_name = 'photos/photo_create.html'
    form_class = PhotoForm
    model = Photo

    def form_valid(self, form):
        photo = form.save(commit=False)
        photo.author = self.request.user
        photo.save()
        form.save_m2m()
        return redirect('webapp:photo_view', pk=photo.pk)


class PhotoUpdateView(PermissionRequiredMixin, UpdateView):
    template_name = 'photos/photo_update.html'
    form_class = PhotoForm
    model = Photo
    context_object_name = 'photo'
    permission_required = 'webapp.change_photo'

    def has_permission(self):
        photo = self.get_object()
        return super().has_permission() or photo.author == self.request.user

    def get_queryset(self):
        return super().get_queryset()

    def get_success_url(self):
        return reverse('webapp:photo_view', kwargs={'pk': self.object.pk})


class PhotoDeleteView(PermissionRequiredMixin, DeleteView):
    template_name = 'photos/photo_delete.html'
    model = Photo
    success_url = reverse_lazy('webapp:index')
    permission_required = 'webapp.delete_photo'

    def has_permission(self):
        photo = self.get_object()
        return super().has_permission() or photo.author == self.request.user

    def has_permission(self):
        return super().has_permission()

    def get_queryset(self):
        return super().get_queryset()


class PhotoChosenView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        photo = get_object_or_404(Photo, pk=kwargs.get('pk'))
        chosen, created = Chosen.objects.get_or_create(image=photo, user=request.user)
        if created:
            photo.save()
            return HttpResponse("Всё хорошо")
        else:
            return HttpResponseForbidden()


class PhotoRemoveView(LoginRequiredMixin, View):
    def delete(self, request, *args, **kwargs):
        photo = get_object_or_404(Photo, pk=kwargs.get('pk'))
        chosen = Chosen.objects.get(image=photo, user=request.user)
        chosen.delete()
        return HttpResponse('Удалён из избранных')

source/webapp/templates/partial/form.html
<form action="{{ action_url }}" method="{{ form_method }}" enctype="{{ enctype }}">
    {% csrf_token %}

    {% for error in form.non_field_errors %}
        <p class="error">{{ error }}</p>
    {% endfor %}

    {% for field in form %}
        {% include 'partial/form_field.html' %}
    {% endfor %}

    <br/>
    <input type="submit" value="{{ button_text|default:"Submit" }}"/>
</form>

source/webapp/templates/partial/form_field.html
{% load widget_tweaks %}

<label for="{{ field.id_for_label }}">
    {% if field.field.required %}
        <span class="red">*</span>
    {% endif %}
    {{ field.label }}:
</label>
<br/>
{% if field|field_type == 'modelmultiplechoicefield' %}
    {{ field|add_class:'form-checkboxes'|add_error_class:'form-error' }}
{% else %}
    {{ field|add_class:'form-input'|add_error_class:'form-error' }}
{% endif %}
<br/>
{% for error in field.errors %}
    <p class="error">{{ error }}</p>
{% endfor %}
<br/>

source/webapp/templates/partial/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="message {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
            message-error
        {% elif message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
            message-warning
        {% elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
            message-success
        {% elif message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
            message-info
        {% else %}
            message-default
        {% endif %}">{{ message }}</div>
    {% endfor %}
{% endif %}

source/webapp/templates/partial/pagination.html
{% load page_utils %}

<div class="pagination">
    <span class="step-links">
        <a href="?{{ request|page_query_string:1 }}">&laquo; В начало</a>

        {% if page_obj.has_previous %}
            <a href="?{{ request|page_query_string:page_obj.previous_page_number }}">Назад</a>
        {% else %}
            <span class="page-disabled">Назад</span>
        {% endif %}


        <form class="current-page" method="get">
            <label for="page">
                {% for key, value in request.GET.items %}
                    {% if not key == 'page' %}
                        <input type="hidden" name="{{ key }}" value="{{ value }}">
                    {% endif %}
                {% endfor %}
                Страница <input type="text" name="page" id="page" value="{{ page_obj.number }}">
                из {{ page_obj.paginator.num_pages }}.
            </label>
        </form>

        {% if page_obj.has_next %}
            <a href="?{{ request|page_query_string:page_obj.next_page_number }}">Далее</a>
        {% else %}
            <span class="page-disabled">Далее</span>
        {% endif %}

        <a href="?{{ request|page_query_string:page_obj.paginator.num_pages }}">В конец &raquo;</a>
    </span>
</div>

source/webapp/templates/partial/photo_list.html
{% load chosens %}
    {% for photo in photos %}
        <div class="card">
            <div class="card-content">
                <br/>
                <p>
                {% if perms.webapp.change_photo or photo.author == request.user %}
                    <a href="{% url 'webapp:photo_update' photo.pk %}" class="card-link" style="padding-right: 3px ">Update <i class="far fa-edit"></i></a>
                {% endif %}
                {% if perms.webapp.delete_photo or photo.author == request.user %}
                    <a href="{% url 'webapp:photo_delete' photo.pk %}" class="card-link">Delete <i class="far fa-trash-alt"></i></a>
                {% endif %}
                </p>
                <a href="{% url 'webapp:photo_view' photo.pk %}"><img class="photo" src="{{ photo.image.url }}" width="auto" height="120" alt="picture"></a>
                <p>Подпись: {{ photo.signature }}<br/>
                Автор: {{ photo.author }}<br/>
                Время создания: {{ photo.created_at }}</p>
                <a class=" add_chosen button accept" style="color: white" href ="{% url 'webapp:photo_choose' photo.pk %}">ADD in FAV</a>
                <a class=" remove_chosen button cancel" style="color: white" href ="{% url 'webapp:photo_remove' photo.pk %}">Remove from FAV</a>

{#                {% if user.is_authenticated %}#}
{#                    {% with photo|chosen_by:user as chosed %}#}
{#                        <a class="{% if chosed %}hidden{% endif %} like" href="{% url 'webapp:photo_choose' photo.pk %}">Like</a>#}
{#                        <a class="{% if not chosed %}hidden{% endif %} unlike" href="{% url 'webapp:article_unlike' article.pk %}">Unlike</a>#}
{#                    {% endwith %}#}
{#                {% endif %}#}
                <br/>
            </div>
        </div>
    {% endfor %}
     {% if is_paginated %}
        {% include 'partial/pagination.html' %}
    {% endif %}